/* WORD BUNDLE FORMAT
    Category, English, Spanish
*/

// Helper to format data for easier editing
function formatBundle(category, rows) {
    return rows.map(row => `${category},${row.join(',')}`).join('\n');
}

const rawBodyParts = formatBundle('Body Part', [
    ["Head", "Cabeza"],
    ["Hair", "Cabello"],
    ["Body Hair", "Pelo"],
    ["Face", "Cara"],
    ["Forehead", "Frente"],
    ["Eye", "Ojo"],
    ["Eyebrow", "Ceja"],
    ["Eyelash", "Pestaña"],
    ["Pupil", "Pupila"],
    ["Nose", "Nariz"],
    ["Nostril", "Fosa Nasal"],
    ["Cheek", "Mejilla"],
    ["Ear", "Oreja"],
    ["Mouth", "Boca"],
    ["Lips | Lip", "Labio | Labios"],
    ["Tooth", "Diente"],
    ["Teeth", "Dientes"],
    ["Tongue", "Lengua"],
    ["Jaw", "Mandíbula"],
    ["Chin", "Barbilla"],
    ["Neck", "Cuello"],
    ["Throat", "Garganta"],
    ["Shoulder", "Hombro"],
    ["Chest", "Pecho"],
    ["Breast", "Chichi"],
    ["Nipple", "Pezón"],
    ["Back", "Espalda"],
    ["Waist", "Cintura"],
    ["Belly Button", "Ombligo"],
    ["Hip", "Cadera"],
    ["Armpit", "Axila"],
    ["Arm", "Brazo"],
    ["Elbow", "Codo"],
    ["Forearm", "Antebrazo"],
    ["Wrist", "Muñeca"],
    ["Hand", "Mano"],
    ["Palm", "Palma"],
    ["Finger", "Dedo"],
    ["Thumb", "Pulgar"],
    ["Pinky | Little Finger", "Meñique"],
    ["Knuckle | Knuckles", "Nudillo"],
    ["Nail", "Uña"],
    ["Buttocks | Butt | Bums | Arse", "Nalgas"],
    ["Leg", "Pierna"],
    ["Thigh", "Muslo"],
    ["Knee", "Rodilla"],
    ["Calf", "Pantorrilla"],
    ["Ankle", "Tobillo"],
    ["Heel", "Talón"],
    ["Foot", "Pie"],
    ["Toe", "Dedo Del Pie"],
    ["Big Toe", "Dedo Gordo"],
    ["Brain", "Cerebro"],
    ["Heart", "Corazón"],
    ["Lungs", "Pulmones"],
    ["Lung", "Pulmón"],
    ["Stomach", "Estómago"],
    ["Bone", "Hueso"],
    ["Skull", "Cráneo"],
    ["Rib", "Costilla"],
    ["Skeleton", "Esqueleto"],
    ["Muscle", "Músculo"],
    ["Blood", "Sangre"],
    ["Vein", "Vena"],
    ["Skin", "Piel"],
    ["Mole", "Lunar"],
    ["Freckle|Freckle", "Peca"],
]);

const rawAnimals = formatBundle('Animals', [
    ["Dog", "Perro"],
    ["Cat", "Gato"],
    ["Mouse", "Ratón"],
    ["Rat", "Rata"],
    ["Hamster", "Hámster"],
    ["Cow", "Vaca"],
    ["Bull", "Toro"],
    ["Horse", "Caballo"],
    ["Donkey", "Burro"],
    ["Pig", "Puerco"],
    ["Sheep", "Oveja"],
    ["Goat", "Chivo"],
    ["Chicken", "Pollo"],
    ["Rooster", "Gallo"],
    ["Duck", "Pato"],
    ["Bird", "Pájaro"],
    ["Toucan", "Tucán"],
    ["Owl", "Búho"],
    ["Bat", "Murciélago"],
    ["Snake", "Culebra"],
    ["Lizard", "Lagartija"],
    ["Iguana", "Iguana"],
    ["Crocodile", "Cocodrilo"],
    ["Turtle", "Tortuga"],
    ["Toad | Frog", "Sapo"],
    ["Fish", "Pescado"],
    ["Shark", "Tiburón"],
    ["Whale", "Ballena"],
    ["Dolphin", "Delfín"],
    ["Octopus", "Pulpo"],
    ["Crab", "Cangrejo"],
    ["Lobster", "Langosta"],
    ["Shrimp", "Camarón"],
    ["Monkey", "Mono"],
    ["Sloth", "Perezoso"],
    ["Tiger", "Tigre"],
    ["Lion", "León"],
    ["Bear", "Oso"],
    ["Wolf", "Lobo"],
    ["Elephant", "Elefante"],
    ["Hippo", "Hipopótamo"],
    ["Anteater", "Oso Hormiguero"],
    ["Ant", "Hormiga"],
    ["Spider", "Araña"],
    ["Fly", "Mosca"],
    ["Bee", "Abeja"],
    ["Cockroach", "Cucaracha"],
    ["Worm", "Gusano"]
]);

const rawEmotions = formatBundle('Emotions', [
    ["Happy", "Feliz"],
    ["Sad", "Triste"],
    ["Annoyed", "Molesto"],
    ["Mad", "Bravo"],
    ["Furious", "Furioso"],
    ["Nervous", "Nervioso"],
    ["Bored", "Aburrido"],
    ["Sleepy", "Cansado"],
    ["Hungry", "Tengo hambre"],
    ["Thirsty", "Tengo sed"],
    ["Drunk", "Borracho"],
    ["Poor", "Sin Dinero"],
    ["Shy", "Tímido"],
    ["Relaxed", "Relajado"],
    ["Good", "Bien"],
    ["Excited", "Emocionado"],
    ["Energetic", "Tengo Energía"],
    ["Lazy", "Perezoso"],
    ["Sick", "Enfermo"],
    ["Bad", "Malo"],
    ["Stressed", "Estresado"],
    ["Worried", "Preocupado"],
    ["Confused", "Confundido"],
    ["Disappointed", "Decepcionado"],
    ["In Love", "Enamorado"],
    ["Arrogant", "Creído"],
    ["Lucky", "Afortunado"],
    ["Unlucky", "Mala Suerte"],
    ["Foolish", "Tonto"],
    ["Intelligent", "Inteligente"],
    ["Crazy", "Loco"],
    ["Nosy", "Curioso"],
    ["Brave", "Valiente"],
    ["Hateful", "Odioso"],
    ["Suspicious", "Sospechoso"],
    ["Overwhelmed", "Agobiado"],
    ["Proud", "Orgulloso"],
    ["Jealous", "Celoso"],
    ["Frustrated", "Frustrado"],
    ["Cold", "Tengo frío"],
    ["Hot", "Tengo calor"],
    ["Surprised", "Sorprendido"],
    ["Uncomfortable", "Incómodo"],
    ["Confident", "Confiado"]
]);

const rawFillerWords = formatBundle('Filler Words', [
    ["Right?", "¿No?"],
    ["Well", "Bueno"],
    ["I Mean", "O Sea"],
    ["Of Course", "Claro"],
    ["The thing is | It's just that", "Es Que"],
    ["So", "Entonces"],
    ["Anyway", "Nada"],
    ["You know?", "¿Sabes?"],
    ["Like", "Tipo"],
    ["Hey | Listen", "Oye"],
    ["Well | So", "Pues"],
    ["Let's see", "A ver"],
    ["The truths", "La Verdad"],
    ["Huh? | Right?", "¿Eh?"],
    ["Seriously", "En Serio"],
    ["Not at all", "Para Nada"],
    ["Exactly", "Exacto"],
    ["For example", "Por ejemplo"],
    ["In the end", "Al Final"],
    ["Look", "Mire | Mira"],
    ["I mean (self-correction)", "Digo"],
    ["Maybe", "A lo mejor"],
    ["Maybe | Regardless", "Igual"],
    ["Obviously", "Obviamente"],
    ["By the way", "Por cierto"],
    ["Do you understand?", "¿Entiendes?"],
    ["I don't know", "Yo qué sé"],
    ["Besides", "Además"],
    ["In fact", "De hecho"],
    ["Even", "Incluso"],
    ["Literally", "Literal"],
    ["No idea", "Ni Idea"],
    ["I swear", "Te lo juro"],
    ["No way", "Qué Va"],
    ["Yes or no?", "Sí o no?"],
    ["Actually", "En realidad"],
    ["I'm telling you", "Te lo digo"],
    ["Well then", "Bueno Pues"],
    ["Exactly like that", "Tal Cual"],
    ["Let's say", "Digamos que"],
    ["By the way", "A todo esto"],
    ["Let me tell you something", "Te digo una cosa"],
    ["Do you get me?", "¿Me explico?"],
    ["Don't you think?", "¿No crees?"],
    ["I promise you", "Te lo prometo"],
    ["In summary", "En Resumen"],
    ["In short", "En pocas palabras"],
    ["Okay (Confirmed)", "Vale"],
    ["Okay (Go Ahead)", "Dale"],
    ["You know what I mean?", "¿Me entiendes?"],
    ["On top of that", "Para colmo"],
    ["You see?", "¿Viste?"],
    ["I told you", "Te lo dije"],
    ["Do you realize?", "¿Te das cuenta?"],
    ["Are you following me?", "¿Me sigues?"],
    ["Evidently", "Evidentemente"],
    ["That being said", "Dicho esto"]
]);

const CUSTOM_VOCAB_BUNDLE_ID = 'bundle_custom_vocab';
const BASE_VOCAB_BUNDLE_IDS = ['bundle_1', 'bundle_2', 'bundle_3', 'bundle_4'];
const CATEGORY_TO_BUNDLE_ID = {
    'Body Part': 'bundle_1',
    'Animals': 'bundle_2',
    'Emotions': 'bundle_3',
    'Filler Words': 'bundle_4'
};

const availableBundles = [
    { id: CUSTOM_VOCAB_BUNDLE_ID, name: '🟡 Custom', data: '' },
    { id: 'bundle_1', name: '🦵 Body Parts', data: rawBodyParts },
    { id: 'bundle_2', name: '🐾 Animals', data: rawAnimals },
    { id: 'bundle_3', name: '😃 Emotions', data: rawEmotions },
    { id: 'bundle_4', name: '💬 Filler Words', data: rawFillerWords }
];