const rawInfinitiveVerbs1 = formatBundle('Infinitive Verbs 1-30', [
    ["To be (permanent)", "Ser"],
    ["To be (temporary)", "Estar"],
    ["To have", "Tener"],
    ["To do | Make", "Hacer"],
    ["To be able to | Can", "Poder"],
    ["To say | Tell", "Decir"],
    ["To go", "Ir"],
    ["To see", "Ver"],
    ["To give", "Dar"],
    ["To know (facts)", "Saber"],
    ["To want | Love", "Querer"],
    ["To arrive", "Llegar"],
    ["To happen | Pass", "Pasar"],
    ["To owe | Must", "Deber"],
    ["To put | Place", "Poner"],
    ["To seem | Appear", "Parecer"],
    ["To stay | Remain", "Quedar"],
    ["To believe", "Creer"],
    ["To speak | Talk", "Hablar"],
    ["To carry | Take", "Llevar"],
    ["To leave | Let", "Dejar"],
    ["To follow | Continue", "Seguir"],
    ["To find | Meet", "Encontrar"],
    ["To call", "Llamar"],
    ["To come", "Venir"],
    ["To think", "Pensar"],
    ["To go out | Leave", "Salir"],
    ["To return", "Volver"],
    ["To take | Drink", "Tomar"],
    ["To know (people/places)", "Conocer"]
]);

_registerBundleData('bundle_6', rawInfinitiveVerbs1);
