const rawInfinitiveVerbs5 = formatBundle('Infinitive Verbs 121-150', [
    ["To greet", "Saludar"],
    ["To say goodbye", "Despedirse"],
    ["To introduce", "Presentar"],
    ["To invite", "Invitar"],
    ["To celebrate", "Celebrar"],
    ["To congratulate", "Felicitar"],
    ["To thank", "Agradecer"],
    ["To apologize", "Disculparse"],
    ["To forgive", "Perdonar"],
    ["To fight | Argue", "Pelear"],
    ["To argue | Discuss", "Discutir"],
    ["To agree", "Acordar"],
    ["To promise", "Prometer"],
    ["To lie", "Mentir"],
    ["To confess", "Confesar"],
    ["To complain", "Quejarse"],
    ["To laugh", "Reír"],
    ["To smile", "Sonreír"],
    ["To cry", "Llorar"],
    ["To shout | Yell", "Gritar"],
    ["To whisper", "Susurrar"],
    ["To joke", "Bromear"],
    ["To flirt", "Coquetear"],
    ["To fall in love", "Enamorarse"],
    ["To get married", "Casarse"],
    ["To get divorced", "Divorciarse"],
    ["To chat casually", "Conversar"],
    ["To gossip", "Chismear"],
    ["To share", "Compartir"],
    ["To meet up | Get together", "Reunirse"]
]);

_registerBundleData('bundle_10', rawInfinitiveVerbs5);
