const rawInfinitiveVerbs3 = formatBundle('Infinitive Verbs 61-90', [
    ["To decide", "Decidir"],
    ["To play", "Jugar"],
    ["To run", "Correr"],
    ["To learn", "Aprender"],
    ["To rest", "Descansar"],
    ["To clean", "Limpiar"],
    ["To cook", "Cocinar"],
    ["To buy", "Comprar"],
    ["To sell", "Vender"],
    ["To eat", "Comer"],
    ["To drink", "Beber"],
    ["To sleep", "Dormir"],
    ["To wake up", "Despertar"],
    ["To walk", "Caminar"],
    ["To swim", "Nadar"],
    ["To dance", "Bailar"],
    ["To sing", "Cantar"],
    ["To play (instrument) | Touch", "Tocar"],
    ["To listen", "Escuchar"],
    ["To help", "Ayudar"],
    ["To ask (a question)", "Preguntar"],
    ["To answer", "Contestar"],
    ["To explain", "Explicar"],
    ["To teach | Show", "Enseñar"],
    ["To study", "Estudiar"],
    ["To practice", "Practicar"],
    ["To repeat", "Repetir"],
    ["To forget", "Olvidar"],
    ["To drive | Manage", "Manejar"],
    ["To travel", "Viajar"]
]);

_registerBundleData('bundle_8', rawInfinitiveVerbs3);
