const rawInfinitiveVerbs8 = formatBundle('Infinitive Verbs 211-240', [
    ["To plant", "Plantar"],
    ["To sow | Seed", "Sembrar"],
    ["To harvest", "Cosechar"],
    ["To water (plants)", "Regar"],
    ["To prune", "Podar"],
    ["To cultivate | Grow (crops)", "Cultivar"],
    ["To grow", "Crecer"],
    ["To bloom | Flower", "Florecer"],
    ["To wither", "Marchitar"],
    ["To recycle", "Reciclar"],
    ["To pollute", "Contaminar"],
    ["To preserve", "Preservar"],
    ["To conserve", "Conservar"],
    ["To protect", "Proteger"],
    ["To hunt", "Cazar"],
    ["To fish", "Pescar"],
    ["To scuba dive | Snorkel", "Bucear"],
    ["To explore", "Explorar"],
    ["To discover", "Descubrir"],
    ["To scale | Climb", "Escalar"],
    ["To camp", "Acampar"],
    ["To sail | Navigate", "Navegar"],
    ["To blow (wind)", "Soplar"],
    ["To rain", "Llover"],
    ["To snow", "Nevar"],
    ["To thunder", "Tronar"],
    ["To flash lightning", "Relampaguear"],
    ["To shine | Gleam", "Brillar"],
    ["To dawn", "Amanecer"],
    ["To get dark", "Oscurecer"]
]);

_registerBundleData('bundle_13', rawInfinitiveVerbs8);
