const rawInfinitiveVerbs4 = formatBundle('Infinitive Verbs 91-120', [
    ["To visit", "Visitar"],
    ["To go up | Climb", "Subir"],
    ["To go down | Descend", "Bajar"],
    ["To close", "Cerrar"],
    ["To break", "Romper"],
    ["To build / Construct", "Construir"],
    ["To destroy", "Destruir"],
    ["To wash", "Lavar"],
    ["To dry", "Secar"],
    ["To iron (clothes)", "Planchar"],
    ["To sew", "Coser"],
    ["To cut", "Cortar"],
    ["To paint", "Pintar"],
    ["To draw", "Dibujar"],
    ["To send", "Enviar"],
    ["To throw", "Tirar"],
    ["To grab | Catch", "Agarrar"],
    ["To push", "Empujar"],
    ["To pull", "Jalar"],
    ["To lift / Raise", "Levantar"],
    ["To carry | Load", "Cargar"],
    ["To jump", "Saltar"],
    ["To fly", "Volar"],
    ["To trip | Stumble", "Tropezar"],
    ["To hit | Strike", "Golpear"],
    ["To kick", "Patear"],
    ["To bite", "Morder"],
    ["To scratch", "Rascar"],
    ["To hug", "Abrazar"],
    ["To kiss", "Besar"]
]);

_registerBundleData('bundle_9', rawInfinitiveVerbs4);
