const rawInfinitiveVerbs7 = formatBundle('Infinitive Verbs 181-210', [
    ["To cure | Heal", "Curar"],
    ["To get sick", "Enfermar"],
    ["To operate | Perform surgery", "Operar"],
    ["To examine", "Examinar"],
    ["To vaccinate", "Vacunar"],
    ["To prescribe", "Recetar"],
    ["To heal | Get better", "Sanar"],
    ["To hurt | Ache", "Doler"],
    ["To injure", "Lastimar"],
    ["To bleed", "Sangrar"],
    ["To breathe", "Respirar"],
    ["To cough", "Toser"],
    ["To sneeze", "Estornudar"],
    ["To yawn", "Bostezar"],
    ["To sweat", "Sudar"],
    ["To tremble | Shake", "Temblar"],
    ["To faint", "Desmayar"],
    ["To recover", "Recuperar"],
    ["To lose weight", "Adelgazar"],
    ["To gain weight", "Engordar"],
    ["To exercise", "Entrenar"],
    ["To warm up", "Calentar"],
    ["To stretch", "Estirar"],
    ["To massage", "Masajear"],
    ["To shave", "Afeitar"],
    ["To comb | Style hair", "Peinar"],
    ["To put on makeup", "Maquillarse"],
    ["To bathe", "Bañarse"],
    ["To shower", "Ducharse"],
    ["To brush (teeth/hair)", "Cepillar"]
]);

_registerBundleData('bundle_12', rawInfinitiveVerbs7);
