const rawInfinitiveVerbs6 = formatBundle('Infinitive Verbs 151-180', [
    ["To pay", "Pagar"],
    ["To charge | Bill", "Cobrar"],
    ["To lend", "Prestar"],
    ["To save (money)", "Ahorrar"],
    ["To spend (money)", "Gastar"],
    ["To invest", "Invertir"],
    ["To negotiate", "Negociar"],
    ["To hire", "Contratar"],
    ["To fire (an employee)", "Despedir"],
    ["To retire", "Jubilarse"],
    ["To manage | Direct", "Dirigir"],
    ["To organize", "Organizar"],
    ["To plan", "Planear"],
    ["To sign", "Firmar"],
    ["To print", "Imprimir"],
    ["To copy", "Copiar"],
    ["To save (a file)", "Guardar"],
    ["To delete", "Borrar"],
    ["To download", "Descargar"],
    ["To install", "Instalar"],
    ["To connect", "Conectar"],
    ["To disconnect", "Desconectar"],
    ["To configure | Set up", "Configurar"],
    ["To program / Code", "Programar"],
    ["To design", "Diseñar"],
    ["To publish", "Publicar"],
    ["To announce", "Anunciar"],
    ["To promote", "Promover"],
    ["To compete", "Competir"],
    ["To resign | Quit", "Renunciar"]
]);

_registerBundleData('bundle_11', rawInfinitiveVerbs6);
