const rawInfinitiveVerbs2 = formatBundle('Infinitive Verbs 31-60', [
    ["To live", "Vivir"],
    ["To feel", "Sentir"],
    ["To try | Treat", "Tratar"],
    ["To look | Watch", "Mirar"],
    ["To count | Tell a story", "Contar"],
    ["To begin | Start", "Empezar"],
    ["To wait | Hope", "Esperar"],
    ["To search | Look for", "Buscar"],
    ["To enter", "Entrar"],
    ["To work", "Trabajar"],
    ["To write", "Escribir"],
    ["To lose", "Perder"],
    ["To understand", "Entender"],
    ["To ask for | Request", "Pedir"],
    ["To receive", "Recibir"],
    ["To remember", "Recordar"],
    ["To finish / End", "Terminar"],
    ["To allow / Permit", "Permitir"],
    ["To get | Obtain", "Conseguir"],
    ["To serve", "Servir"],
    ["To take out", "Sacar"],
    ["To need", "Necesitar"],
    ["To maintain | Keep", "Mantener"],
    ["To read", "Leer"],
    ["To fall", "Caer"],
    ["To change", "Cambiar"],
    ["To create", "Crear"],
    ["To open", "Abrir"],
    ["To win | Earn", "Ganar"],
    ["To use", "Usar"]
]);

_registerBundleData('bundle_7', rawInfinitiveVerbs2);
