const rawAnimals = formatBundle('Animals', [
    ["Dog", "Perro"],
    ["Cat", "Gato"],
    ["Mouse", "Ratón"],
    ["Rat", "Rata"],
    ["Hamster", "Hámster"],
    ["Cow", "Vaca"],
    ["Bull", "Toro"],
    ["Horse", "Caballo"],
    ["Donkey", "Burro"],
    ["Pig", "Puerco"],
    ["Sheep", "Oveja"],
    ["Goat", "Chivo"],
    ["Chicken", "Pollo"],
    ["Rooster", "Gallo"],
    ["Duck", "Pato"],
    ["Bird", "Pájaro"],
    ["Toucan", "Tucán"],
    ["Owl", "Búho"],
    ["Bat", "Murciélago"],
    ["Snake", "Culebra"],
    ["Lizard", "Lagartija"],
    ["Iguana", "Iguana"],
    ["Crocodile", "Cocodrilo"],
    ["Turtle", "Tortuga"],
    ["Toad | Frog", "Sapo"],
    ["Fish", "Pescado"],
    ["Shark", "Tiburón"],
    ["Whale", "Ballena"],
    ["Dolphin", "Delfín"],
    ["Octopus", "Pulpo"],
    ["Crab", "Cangrejo"],
    ["Lobster", "Langosta"],
    ["Shrimp", "Camarón"],
    ["Monkey", "Mono"],
    ["Sloth", "Perezoso"],
    ["Tiger", "Tigre"],
    ["Lion", "León"],
    ["Bear", "Oso"],
    ["Wolf", "Lobo"],
    ["Elephant", "Elefante"],
    ["Hippo", "Hipopótamo"],
    ["Anteater", "Oso Hormiguero"],
    ["Ant", "Hormiga"],
    ["Spider", "Araña"],
    ["Fly", "Mosca"],
    ["Bee", "Abeja"],
    ["Cockroach", "Cucaracha"],
    ["Worm", "Gusano"]
]);

_registerBundleData('bundle_2', rawAnimals);
