const rawBodyParts = formatBundle('Body Part', [
    ["Head", "Cabeza"],
    ["Hair", "Cabello"],
    ["Body Hair", "Pelo"],
    ["Face", "Cara"],
    ["Forehead", "Frente"],
    ["Eye", "Ojo"],
    ["Eyebrow", "Ceja"],
    ["Eyelash", "Pestaña"],
    ["Pupil", "Pupila"],
    ["Nose", "Nariz"],
    ["Nostril", "Fosa Nasal"],
    ["Cheek", "Mejilla"],
    ["Ear", "Oreja"],
    ["Mouth", "Boca"],
    ["Lips | Lip", "Labio | Labios"],
    ["Tooth", "Diente"],
    ["Teeth", "Dientes"],
    ["Tongue", "Lengua"],
    ["Jaw", "Mandíbula"],
    ["Chin", "Barbilla"],
    ["Neck", "Cuello"],
    ["Throat", "Garganta"],
    ["Shoulder", "Hombro"],
    ["Chest", "Pecho"],
    ["Back", "Espalda"],
    ["Waist", "Cintura"],
    ["Belly Button", "Ombligo"],
    ["Hip", "Cadera"],
    ["Armpit", "Axila"],
    ["Arm", "Brazo"],
    ["Elbow", "Codo"],
    ["Forearm", "Antebrazo"],
    ["Wrist", "Muñeca"],
    ["Hand", "Mano"],
    ["Palm", "Palma"],
    ["Finger", "Dedo"],
    ["Thumb", "Pulgar"],
    ["Pinky | Little Finger", "Meñique"],
    ["Knuckle | Knuckles", "Nudillo"],
    ["Nail", "Uña"],
    ["Buttocks | Butt | Bums | Arse", "Nalgas"],
    ["Leg", "Pierna"],
    ["Thigh", "Muslo"],
    ["Knee", "Rodilla"],
    ["Calf", "Pantorrilla"],
    ["Ankle", "Tobillo"],
    ["Heel", "Talón"],
    ["Foot", "Pie"],
    ["Toe", "Dedo Del Pie"],
    ["Big Toe", "Dedo Gordo"],
    ["Brain", "Cerebro"],
    ["Heart", "Corazón"],
    ["Lungs", "Pulmones"],
    ["Lung", "Pulmón"],
    ["Stomach", "Estómago"],
    ["Bone", "Hueso"],
    ["Skull", "Cráneo"],
    ["Rib", "Costilla"],
    ["Skeleton", "Esqueleto"],
    ["Muscle", "Músculo"],
    ["Blood", "Sangre"],
    ["Vein", "Vena"],
    ["Skin", "Piel"],
    ["Mole", "Lunar"],
    ["Freckle|Freckle", "Peca"],
]);

_registerBundleData('bundle_1', rawBodyParts);
