const rawEmotions = formatBundle('Emotions', [
    ["Happy", "Feliz"],
    ["Sad", "Triste"],
    ["Annoyed", "Molesto"],
    ["Mad", "Bravo"],
    ["Furious", "Furioso"],
    ["Nervous", "Nervioso"],
    ["Bored", "Aburrido"],
    ["Sleepy", "Cansado"],
    ["Hungry", "Tengo hambre"],
    ["Thirsty", "Tengo sed"],
    ["Drunk", "Borracho"],
    ["Poor", "Sin Dinero"],
    ["Shy", "Tímido"],
    ["Relaxed", "Relajado"],
    ["Good", "Bien"],
    ["Excited", "Emocionado"],
    ["Energetic", "Tengo Energía"],
    ["Lazy", "Perezoso"],
    ["Sick", "Enfermo"],
    ["Bad", "Malo"],
    ["Stressed", "Estresado"],
    ["Worried", "Preocupado"],
    ["Confused", "Confundido"],
    ["Disappointed", "Decepcionado"],
    ["In Love", "Enamorado"],
    ["Arrogant", "Creído"],
    ["Lucky", "Afortunado"],
    ["Unlucky", "Mala Suerte"],
    ["Foolish", "Tonto"],
    ["Intelligent", "Inteligente"],
    ["Crazy", "Loco"],
    ["Nosy", "Curioso"],
    ["Brave", "Valiente"],
    ["Hateful", "Odioso"],
    ["Suspicious", "Sospechoso"],
    ["Overwhelmed", "Agobiado"],
    ["Proud", "Orgulloso"],
    ["Jealous", "Celoso"],
    ["Frustrated", "Frustrado"],
    ["Cold", "Tengo frío"],
    ["Hot", "Tengo calor"],
    ["Surprised", "Sorprendido"],
    ["Uncomfortable", "Incómodo"],
    ["Confident", "Confiado"]
]);

_registerBundleData('bundle_3', rawEmotions);
