const rawFillerWords = formatBundle('Filler Words', [
    ["Right?", "¿No?"],
    ["Well", "Bueno"],
    ["I Mean", "O Sea"],
    ["Of Course", "Claro"],
    ["The thing is | It's just that", "Es Que"],
    ["So", "Entonces"],
    ["Anyway | Nothing" , "Nada"],
    ["You know?", "¿Sabes?"],
    ["Like", "Tipo"],
    ["Hey | Listen", "Oye"],
    ["Well | So", "Pues"],
    ["Let's see", "A ver"],
    ["The truths", "La Verdad"],
    ["Huh? | Right? | What?", "¿Eh? | ¿Qué?"],
    ["Seriously", "En Serio"],
    ["Not at all", "Para Nada"],
    ["Exactly", "Exacto"],
    ["For example", "Por ejemplo"],
    ["In the end", "Al Final"],
    ["Look", "Mire | Mira"],
    ["I mean (self-correction)", "Digo"],
    ["Maybe", "A lo mejor"],
    ["Maybe | Regardless", "Igual"],
    ["Obviously", "Obviamente"],
    ["By the way", "Por cierto"],
    ["Do you understand?", "¿Entiendes?"],
    ["I don't know", "Yo qué sé"],
    ["Besides", "Además"],
    ["In fact", "De hecho"],
    ["Even", "Incluso"],
    ["Literally", "Literal"],
    ["No idea", "Ni Idea"],
    ["I swear", "Te lo juro"],
    ["No way", "Qué Va"],
    ["Yes or no?", "Sí o no?"],
    ["Actually", "En realidad"],
    ["I'm telling you", "Te lo digo"],
    ["Well then", "Bueno Pues"],
    ["Exactly like that", "Tal Cual"],
    ["Let's say", "Digamos que"],
    ["By the way", "A todo esto"],
    ["Let me tell you something", "Te digo una cosa"],
    ["Do you get me?", "¿Me explico?"],
    ["Don't you think?", "¿No crees?"],
    ["I promise you", "Te lo prometo"],
    ["In summary", "En Resumen"],
    ["In short", "En pocas palabras"],
    ["Okay (Confirmed)", "Vale"],
    ["Okay (Go Ahead)", "Dale"],
    ["On top of that", "Para colmo"],
    ["You see?", "¿Viste?"],
    ["I told you", "Te lo dije"],
    ["Do you realize?", "¿Te das cuenta?"],
    ["Are you following me?", "¿Me sigues?"],
    ["Evidently", "Evidentemente"],
    ["That being said", "Dicho esto"]
]);

_registerBundleData('bundle_4', rawFillerWords);
