const rawPanamanianPhrases = formatBundle('Panamanian-Specific Terms', [
    ["What's up?", "Qué sopa | Que lo que"],
    ["Sure", "Dale pues"],
    ["Okay", "Ofi"],
    ["A lot", "Buco"],
    ["Head", "Chonta"],
    ["Friend", "Fren"],
    ["Beer", "Pinta"],
    ["Car", "Nave"],
    ["Thing", "Vaina"],
    ["Fancy person | Posh", "Yeye"],
    ["Junk food", "Burundanga"],
    ["No money | Broke", "Tas limpio"],
    ["House", "Chaintin"],
    ["Tell me the gossip", "Cuéntame la cocoa"],
    ["Blond", "Fulo"],
    ["A slap", "Soplampco"],
    ["Devil bus", "Diablo rojo"],
    ["Dumb person", "Awebado"],
    ["Low life | Homeless person", "Un piedrero"],
    ["Lazy person", "Bulto"],
    ["Low quality", "Panga"],
    ["Cousin", "Mopri"],
    ["Music", "Plena"],
    ["To greet", "Chotear"],
    ["To text", "Chatear"],
    ["To dodge | To avoid", "Chifear"],
    ["Check this out", "Pilla"],
    ["To joke around | To tease", "Bacilar"],
    ["You crushed it | Above expectations", "La botaste"],
    ["Great food", "Rantan"],
    ["Messy situation", "Arroz con mango"],
    ["I forgot", "Chuleta"],
    ["Take care", "Cuídate pues"],
    ["Looking good", "Bien tallao"],
    ["I'm tired", "Estoy tiaro"],
    ["Unexpected situation", "Qué ponchera"],
    ["Maybe", "quizás"]
]);

_registerBundleData('bundle_5', rawPanamanianPhrases);
